/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`tests/fictional.test.js TAP generated values > must match snapshot 1`] = `
Array [
  Object {
    "bool": true,
    "dateString": "2017-06-10T05:23:20.000Z",
    "float": 2705143667.205281,
    "hash": 177557,
    "int": 177557,
    "join": "Cherry Road",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Kanefu mafu wohonane hờya yatotaŷo muyure yǒ ƙosurote, tsunoriyu miyota nënihe sohishire raha. Sechiyumo komeṅono yori shiromi niraru chi. Tanohaho takuǹe suteko fuwońoku kumisuhé se kŮ, nomanoru no ṥhiruyu semochine tachinaḱa niḱo ninano. Nanuse ǩarafume kởmu fuhitsu kasuchi samoha sene ruseso. Kitaya tẽ rikeruna neyo rama ẘa rirǒnama, su shi yæte ḿamu chikemi furusa yo.",
    "sentence": "Ruka toya surimu meku re royowaya, nutekinū̃ hế ḣe noyuto shi nu tohotsu.",
    "someOf": Array [
      "are",
      "too",
      "you",
      "think",
      "i",
    ],
    "times": Array [
      "Rome",
      "Sonanuho",
      "Ȟano",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Munamựta",
    "words": "Nasa m̃ashi ņe",
  },
  Object {
    "bool": false,
    "dateString": "2016-05-09T04:22:19.000Z",
    "float": 2705143570.275906,
    "hash": 177556,
    "int": 177556,
    "join": "Parkway Street",
    "oneOf": "green",
    "oneOfWeighted": "blue",
    "paragraph": "Teṛu ⱨerini chikesa ri sehamo kehishiri musorihe, ṉonuka mimeĉhitsu ku cĥitenunu ke to tsukukafu henayunớ. Kēkarosa katera hoyo tsutasa sashiku ṃa meyợrumi. Ruyuho koha kuwa shiŧo kusaḱi nanãmuwa. Rè̩ nesủ notsuheki horosośhi sarakuwa kohoshiya mofune rufutara.",
    "sentence": "Nehokaki kả ho ha chimote teshiyaro.",
    "someOf": Array [
      "colors",
      "it",
      "are",
      "i",
    ],
    "times": Array [
      "Wonomi",
      "Yąnuyo",
    ],
    "tuple": Array [
      "Parkway",
      "Street",
    ],
    "word": "Saheha",
    "words": "Miraṫeta tsuwosőyo",
  },
  Object {
    "bool": true,
    "dateString": "2019-08-12T07:25:22.000Z",
    "float": 2705143601.1919847,
    "hash": 177559,
    "int": 177559,
    "join": "Parkway Street",
    "oneOf": "green",
    "oneOfWeighted": "red",
    "paragraph": "Rahẚ yutariro shishi mikemana haka, saraya ţa romo somimewa yuchishito. Kikeshishi newanoku sa tonoko hờ tone. Hate hahiro yorerura so yasonena matehi, nṹsunaro ẁatomu mamāte koshinoma kimutsu himuhomo ho kesosa. Ķaromi na tasonû niyokete yoto ni, so no ṙenuchi ṡatare misato tsusæ. Risu tosoruka yo rimu wake sahihã kiyaruꝁa, wohotsuse shɨchi ḩareya sū ḫe kuɏa.",
    "sentence": "No miho fuȓu hêchiwa m̃uyo su, ṃemuse sħi ħi yochi ya nĭ.",
    "someOf": Array [
      "that",
      "beautiful",
      "are",
      "think",
    ],
    "times": Array [
      "Kum̃i",
      "Shito̩sechi",
      "Ramoto",
      "Nirire",
      "Sę́sena",
    ],
    "tuple": Array [
      "Parkway",
      "Street",
    ],
    "word": "Rosato",
    "words": "Woruwo shiwata nuyurẳ",
  },
  Object {
    "bool": false,
    "dateString": "2018-07-11T06:24:21.000Z",
    "float": 2705143760.1084604,
    "hash": 177558,
    "int": 177558,
    "join": "Privet Road",
    "oneOf": "red",
    "oneOfWeighted": "blue",
    "paragraph": "Tsurosaɽu runḁ somo rehari ŗari. Ririne tese kichĩruho seri fuhihise shikiru, tora yu katahi wa kǫtoma ƫe. Hinumahe tokamomu mohise menuso ŝekenure. Romònu hemine yoyo ro shiyusuko né̩ ŗoso.",
    "sentence": "Shishiẉa ṃuke řa narehohe matsu.",
    "someOf": Array [
      "are",
      "you",
      "256",
    ],
    "times": Array [
      "Yore",
      "Naruka",
      "Riyoyaku",
      "Kỉyumi",
    ],
    "tuple": Array [
      "Privet",
      "Road",
    ],
    "word": "Haso",
    "words": "Kẳ tasokeri",
  },
  Object {
    "bool": true,
    "dateString": "2013-02-06T01:19:16.000Z",
    "float": 2705143799.3086195,
    "hash": 177553,
    "int": 177553,
    "join": "Cherry Road",
    "oneOf": "green",
    "oneOfWeighted": "red",
    "paragraph": "Kanike fuyuro wakŭke komanu nu. Minishino kimuroro tetsutara musemeka taroru tsu, rarỏmi tesa niyamenu ṱeni tậtsu m̃o. Mosa mi së yoneyara yochiniho yaṁima, runis̩u ra wam̃eresu waruhi naso suhahako. Ņunerowa ňanofu karu moyo henaḿu. Romemishi ṁohahonu niseṋeke ki fṵmira yữ keśa, re nena rɵrari ro ḣite tsu.",
    "sentence": "Yumi tsune se hȋ mo koyŭ raḣi, wahiyoku natsuha yariwa su ho shitokeỷa noshinỗto.",
    "someOf": Array [
      "is",
      "think",
      "256",
      "that",
    ],
    "times": Array [
      "Satę̃",
      "Rầfuka",
      "Họsu",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Tsumaso",
    "words": "Koriraho yusāsawo cⱨi",
  },
  Object {
    "bool": false,
    "dateString": "2012-01-05T00:18:15.000Z",
    "float": 2705143702.1874986,
    "hash": 177552,
    "int": 177552,
    "join": "Cherry Road",
    "oneOf": "red",
    "oneOfWeighted": "blue",
    "paragraph": "Rurư yafuke shi rasushiṃo teyuko, wosami ni yo kate tefuwara. Rahe hasa yarutota homisuyu manȉ yu ṁi yufunuchĭ, nȏ nofu yæmo ṧukiko hami ninṑhi hota. Nasehe kaniyumo kanike nitoshi mashiyafu ninuneḿa re nese. Heroṋono ho ǩi muyo ⱦanowo sǻ chi wo, nine mafuỵuna yaso motsu yanora no.",
    "sentence": "Nosotasu ya yarite nokerufu ko ha ṙi.",
    "someOf": Array [
      "that",
      "beautiful",
      "too",
    ],
    "times": Array [
      "Nukumos̈a",
      "Yuyamus̈u",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Yani",
    "words": "Fū ku",
  },
  Object {
    "bool": true,
    "dateString": "2015-04-08T03:21:18.000Z",
    "float": 2705143733.33078,
    "hash": 177555,
    "int": 177555,
    "join": "Cherry Road",
    "oneOf": "red",
    "oneOfWeighted": "green",
    "paragraph": "Rora ĥaru kumo ŕe hamomumu. Ṛoratsu toko sȯ keho ⱪeha rosowo tokese fuchi, runuyu yonoshihì sể riyuru maỵora yosuke hisa. Yử ma rumo ri mokiya raneyoḵi ro. Rano sori yuyatamo ɍekeri tahehirȋ, rehẳ yaḟuneku nasu ne fusȟi ꞧimukoso ṋuso. Hitama șuha ka rutewone nayamiro nusoka hoyo sariminu.",
    "sentence": "Na tsuyanuki tsuku kufu ke niromuko kiku ṋu, ņaro funakihe risǟ rê̌ hiwahise shikoyutsu kuneňe hawamo.",
    "someOf": Array [
      "i",
      "it",
      "256",
    ],
    "times": Array [
      "Keseyu",
      "Tarusū̀tsu",
      "Mihose",
      "Rǔhi",
      "Mukore",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Rawa",
    "words": "Yomoƴune yumunĕ ku",
  },
  Object {
    "bool": false,
    "dateString": "2014-03-07T02:20:17.000Z",
    "float": 2705143892.4052486,
    "hash": 177554,
    "int": 177554,
    "join": "Cherry Drive",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Ka ko hiruyo heshi ne wo, no he nasḧi nemuhe ruhiho ỵosayu. Kahenono honori ki to mï nakome. Ru mi ka ka sa. Hi ya kino su niyukɨ miraku, mutatsu waṅi râ sese ranicḧi yusuri.",
    "sentence": "Retēwani rinenato wo yo niteťe noroyosu nayaruhi ḱuwaso.",
    "someOf": Array [
      "you",
      "that",
      "256",
      "it",
      "i",
    ],
    "times": Array [
      "Muwato",
      "Ƙanumise",
      "Ŵasu",
      "Sumemṏhe",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Yorekarṵ",
    "words": "Șesato soýu",
  },
  Object {
    "bool": true,
    "dateString": "1985-02-18T13:31:28.000Z",
    "float": 2705143419.151939,
    "hash": 177565,
    "int": 177565,
    "join": "Cherry Drive",
    "oneOf": "green",
    "oneOfWeighted": "red",
    "paragraph": "Wakařete se hekese nunote seha su waseno tsuchisa, hi washiraro sặ ho yo mirihama hḗmetora ⱨotaro. Ni kamiwa serumo hohifu kani sunehę̃ ķatosa, masateno ʈe muke shimuĥo niruyayu. Yosawō wowo reto kohekosa kosa, ke yoruyuma ẉo ni hańu ƙikewoso chiratsushi haseke. Minàseku ma ṅekire nohehose hoka yatsu. Muteyo fụ ka ṃi hę reme mų̃.",
    "sentence": "Sekeyŏ tsu hanikota koẏa renuchi rowaⱨone shihikoho ta, matorusu himu nunarena tsuȟe kekukaro.",
    "someOf": Array [
      "it",
      "that",
      "is",
      "colors",
    ],
    "times": Array [
      "Hakikofu",
      "Rayä",
      "Tamoma",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Ritehi",
    "words": "Kuwợ ya tari",
  },
  Object {
    "bool": false,
    "dateString": "1984-01-17T12:30:27.000Z",
    "float": 2705143322.50167,
    "hash": 177564,
    "int": 177564,
    "join": "Privet Drive",
    "oneOf": "red",
    "oneOfWeighted": "blue",
    "paragraph": "Manu čhi rasemi ṃo ruḵo tšukete hi, fumukafu nokiteme mōfu yufŮsa yu teroro. Ṃuwa shimichishi yo fuhehitsu nukorofu mamoƫeno nutsukṏ meme. Ẇayo wanehę̃ sewowa komanikȫ shiyu yohesemo. Yumuso kohosoni ḟu tomė́ mame.",
    "sentence": "Hợ yanefu ta yurite mi kere.",
    "someOf": Array [
      "i",
      "think",
      "that",
    ],
    "times": Array [
      "Rohanoko",
      "Torehoya",
    ],
    "tuple": Array [
      "Privet",
      "Drive",
    ],
    "word": "Kesḧi",
    "words": "Reke yạ",
  },
  Object {
    "bool": false,
    "dateString": "1992-09-25T20:39:59.000Z",
    "float": 3370392162.2247863,
    "hash": 5859332,
    "int": 5859332,
    "join": "Privet Road",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Ma yunahe tẩ shi ho yokayu tã suseta. Yuṉe śu chimu tȁsu newaroni sufuma. Máranu so ḥeke kere nuké̩neke ri wamarị. Menumi yochirane woẏusu yoshiḩiwa notochi, kamu hotomaha yohe yahimi satamino.",
    "sentence": "He nuwa tsu m̃oma mĕhomu hamahȫku mawo ka.",
    "someOf": Array [
      "are",
      "256",
      "i",
      "too",
      "you",
    ],
    "times": Array [
      "Toruha",
      "Rane",
    ],
    "tuple": Array [
      "Privet",
      "Road",
    ],
    "word": "Waseheķe",
    "words": "Ru ŗokama",
  },
  Object {
    "bool": true,
    "dateString": "1985-06-02T05:13:32.000Z",
    "float": 3370395171.8190584,
    "hash": 5859365,
    "int": 5859365,
    "join": "Cherry Drive",
    "oneOf": "blue",
    "oneOfWeighted": "blue",
    "paragraph": "Hokê̌tari chihạ s̩hika tenimo ruhimiwo kise. Sasuṯsute yuriňi chitoku ta rumose ruhowo suṁaneke. Șe rini hōnuha tsu ķi shihamu monoke seyunume. Tsurekure ha nemitaku momi neẃo kiretame nuchichire horefu, miworuyu wato tatsū̀no nỡmo meme ne. Koŗa ķa renesểno ÿu chimurumu mimemi.",
    "sentence": "Roḥemohi re wama re nễtsuma nuṟu ke miriḧemu, mofure hihekǜhe tomikonu nanehi kosoko ko heshi.",
    "someOf": Array [
      "too",
      "256",
      "are",
      "is",
      "it",
    ],
    "times": Array [
      "Ranu",
      "Tonấ",
      "Waku",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Hanȯkuko",
    "words": "Saẗaku rutesa kasukone",
  },
  Object {
    "bool": false,
    "dateString": "2018-03-07T14:47:05.000Z",
    "float": 3370394336.377823,
    "hash": 5859398,
    "int": 5859398,
    "join": "Cherry Street",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Towayahæ nitsuse wokaranu hasehoni terotasa mora sanafu ma. Hikeyama nirāho riyuheso hamita tarera himotani cḩi, rayuyu tonoẙo ḧara roḥi tsư. Minete wǫ hi ka mororu hikiworo he, tsuneta nuyaṁena sakasa teneneta numichi. Mero masamakê̌ mini ta chihá tesuseto shimosu, hosameko ma woyono ta mi setokafu.",
    "sentence": "Mo ẘo mufu sutese shifu kḝnema tanaku hora.",
    "someOf": Array [
      "you",
      "that",
      "it",
      "i",
      "think",
    ],
    "times": Array [
      "Teyate",
      "Kenishi",
      "Seramunầ",
      "Nohemera",
    ],
    "tuple": Array [
      "Cherry",
      "Street",
    ],
    "word": "Yanumomo",
    "words": "Hoteho hesê",
  },
  Object {
    "bool": true,
    "dateString": "2011-12-12T23:20:38.000Z",
    "float": 3370397345.544538,
    "hash": 5859431,
    "int": 5859431,
    "join": "Privet Road",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Ni mochini hemiwo nekoƈhiwo tososa shiyokộ, ka yańo fuyo ruru mowofu muwo. Ȟe ka tĕmimo roso miwoyuni rȉ sora semo. Niso sutohise nanor̃unu ha nahe, so newa yumuse kṵho mimikara ka mereyona. Kê̌ mänu rosu tosể torứru hikuri chisȟikira neki. Sum̃uni mesowo yuwano sȭ sahikatšu neké̩.",
    "sentence": "Hawona seḉhiri tehekafu tosahê̄he hiku riwamanu hi somuso, sarĭ tȱ teḿekate hiyatą́so yutsū̃se kukǎchi.",
    "someOf": Array [
      "256",
      "beautiful",
      "i",
      "you",
      "are",
    ],
    "times": Array [
      "Tesuta",
      "Kaheshḯre",
      "Memứkote",
      "Kiki",
      "Saya",
    ],
    "tuple": Array [
      "Privet",
      "Road",
    ],
    "word": "Kuyunuse",
    "words": "Ka yohaheya notsu",
  },
  Object {
    "bool": false,
    "dateString": "1980-09-05T08:25:47.000Z",
    "float": 3370396518.794216,
    "hash": 5859200,
    "int": 5859200,
    "join": "Parkway Drive",
    "oneOf": "blue",
    "oneOfWeighted": "blue",
    "paragraph": "Sumò tehokamầ wẫchi me ranuhe yǘyu ketomusu. Kȋsa hinosune seneŗite moyute rasachi matsu tesorawo. Rikoha hi wa re muyamuta tekå muwoyu nẚ, kuyatsu keḟumo fumoyuno r̃u kusoyaḱu. Wanoto ĥisehi ẖa heře ṅurotsu rimure nayona kike, rī̀ mi so tsuḩi tsufuteku.",
    "sentence": "Roka tsu hifuŵa so ruketsu rį̃na ta yatakoha.",
    "someOf": Array [
      "it",
      "colors",
      "are",
      "beautiful",
      "i",
    ],
    "times": Array [
      "Kekī̀fuwa",
      "Kowore",
    ],
    "tuple": Array [
      "Parkway",
      "Drive",
    ],
    "word": "Chiyasuŗe",
    "words": "Rufu wa",
  },
  Object {
    "bool": true,
    "dateString": "2013-06-10T17:59:20.000Z",
    "float": 3370399527.225363,
    "hash": 5859233,
    "int": 5859233,
    "join": "Cherry Road",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Ko wąmu nuneyȧni yuwowono tahone rafu yomowa meḧa. Teshika hashiya mina heha mĭ, yarṹ na hihehefu nihi yomehiró̩. Meheḟu ẘatetsu semomiyo çhisu chinaruku ṭe rukoneso chihồ. Soharoṁo ya kừ sute nayu. Ku hą́wanachi šhinokoko wayakǒke sukete sḣiki ȟiru kore, ronu chikayachi rï yonutone keso teme sawochīki.",
    "sentence": "Satsurishi shikeke nowono wotà rȫ nito, hoyẚha fu hiyuchine kerarehi mekuhṏwa hè̩wa.",
    "someOf": Array [
      "colors",
      "is",
      "you",
      "too",
      "i",
    ],
    "times": Array [
      "Mema",
      "Yunirore",
      "Tekenể",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Fumesemớ",
    "words": "Hematṩu tochi fufushi",
  },
  Object {
    "bool": false,
    "dateString": "2006-03-15T02:32:53.000Z",
    "float": 3370398692.1807475,
    "hash": 5859266,
    "int": 5859266,
    "join": "Privet Road",
    "oneOf": "blue",
    "oneOfWeighted": "blue",
    "paragraph": "Fuchiṇa chihayu chi ṙe tsucħikaki yŏ. Rokare runomi yanowa newoyomi riki kû ruwoⱨa kutsuşe. Hifu yotahoki hoha kanunuse ňa namitsune, ẇanachiyu yorốnu tafuwoyo koyayune yanê̌sa kineyu ꝁe. Kisuwoso na koňumu ne ṃu sakenonu sufu.",
    "sentence": "Kȫ rimufu mo ɽero shi museho.",
    "someOf": Array [
      "that",
      "colors",
      "you",
      "i",
      "it",
    ],
    "times": Array [
      "Tem̃e",
      "Ⱦaha",
      "Chiŝusosa",
      "Homa",
    ],
    "tuple": Array [
      "Privet",
      "Road",
    ],
    "word": "Sowamete",
    "words": "Ƙimewoso chiho",
  },
  Object {
    "bool": true,
    "dateString": "1999-12-20T12:06:26.000Z",
    "float": 3370401701.303176,
    "hash": 5859299,
    "int": 5859299,
    "join": "Parkway Road",
    "oneOf": "blue",
    "oneOfWeighted": "blue",
    "paragraph": "Tawotofǔ shiwafuta watsu kuha hȧ maŧefu fuyasowa tamenằ. Heketa mume ne tê̌ku kakima ka shihikumu ⱨoro, hero ya mê̄ya ronunesa wońomu shihe. Kichitesa hatsuro nemuwo wǎ fuka rurure ṁonuni, mo horamimó̩ haro sus̈hi tawa ⱪi mosuwaḱu. Shi ňimeni ka taru ẗsurakefu, to heniⱨa shiko tanuni natohama naronuni soki. Hayoyu memi wanoŗo yumarɵ nakusa ǩeyayu, mukahį̃ko ṁa moyatsuhi seri namuni yomihowa.",
    "sentence": "Sokoya rasoru yakiwote yatome shikaḟu, naṁenuni nohi tṣu ma yowomeme kitewa cħisu.",
    "someOf": Array [
      "think",
      "are",
      "beautiful",
      "too",
      "colors",
    ],
    "times": Array [
      "Ratorume",
      "Yarê̄",
      "Yowaṟe",
      "Ronofuku",
      "Nateyuyu",
    ],
    "tuple": Array [
      "Parkway",
      "Road",
    ],
    "word": "Watetore",
    "words": "Minayoke muǹekihe rote",
  },
  Object {
    "bool": false,
    "dateString": "2016-09-09T21:08:23.000Z",
    "float": 3370383466.1667266,
    "hash": 5859596,
    "int": 5859596,
    "join": "Cherry Drive",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Nahe kinekuyu wowotahi tě mesorori, nashi torǖ ki mumese mamo. Ri re makiriri țsukokete mi momȱ romirų́ sonu, niyasete resoyoru mamǡne renȁ haraneňo ko s̩ukowome shiĉhi. Re yotaku nề futsuṃene he. Hiẁo kusasa sufu chiyuho kusaną́ ṡe moko yutsuṃo.",
    "sentence": "Tonokuwa hį kira keyowako te.",
    "someOf": Array [
      "is",
      "it",
      "colors",
      "256",
      "are",
    ],
    "times": Array [
      "Minose",
      "Risetsuna",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Yamemumu",
    "words": "Kuyuyuha neshi",
  },
  Object {
    "bool": true,
    "dateString": "2009-06-14T05:41:56.000Z",
    "float": 3370386475.2931623,
    "hash": 5859629,
    "int": 5859629,
    "join": "Cherry Street",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Kếsu temo waᶄino sämori mu rayaku ḥenure, ẗe himu nisuƙa me hokemechi. Nimuhete mohe nishihe ṇeshi nuțemi mima terakashi nonona. Ranuḿoso kitsu hakoshi nu ƒunari rẚ chimớre. Se seme hịchime su tsuheshi nutsuno tasemi hiṙa, wose keriwởhe ḟuto sỗheri nomushimu shį̃no kimitsu ŗuno. Nu tsu kutsuru kiÿu nini ta ke kù, nakohero sesatā̀ sorusoꝁa chisatsu ha hisuku hiʈase.",
    "sentence": "Mani kï runuyuse mo yarehiyo mururamo mehaŕuma yowo, kokimeso wa makuruma ri ṝeku mihemeha mohato naku.",
    "someOf": Array [
      "256",
      "it",
      "that",
      "you",
      "are",
    ],
    "times": Array [
      "Heyayonu",
      "Satomumu",
      "Momi",
    ],
    "tuple": Array [
      "Cherry",
      "Street",
    ],
    "word": "Mayohaka",
    "words": "Wo numaṁi kurosoya",
  },
  Object {
    "bool": true,
    "dateString": "1995-12-28T23:43:02.000Z",
    "float": 3370392065.3310738,
    "hash": 5859335,
    "int": 5859335,
    "join": "Cherry Road",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Tsuke mehamishi nanohoshi ƫoya rufute tǟnure nuǹe, chiseruno té̩wachi nosẳ niri te shi. Tě tasuyoma tsu ⱪushise kashikane rû, sarete no tsuyukì shishiruso ḧokifuchi. Sehiyara rori ḿuho ñe mi rowatsuri. Ka kotake yorushiħe kĩwo kohi ṋe yaroka, rį rana ꞧofu ta yarênuru mi. Ⱪoma retsuyo maꞩamu tarẹki ḟuri nasutato kĭ.",
    "sentence": "Fusoya rehiwo ko saniṅi yu homacḫi, waremamé me ritsusùsa moẗefu naku tsume sunuroni.",
    "someOf": Array [
      "that",
      "beautiful",
      "too",
      "256",
      "it",
    ],
    "times": Array [
      "Shiyotoshi",
      "Nosḩiwonu",
      "Hekari",
      "Tese",
      "Ḟumuhi",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Nutohete",
    "words": "Ɽa ḵiha kusonoho",
  },
  Object {
    "bool": false,
    "dateString": "1986-07-03T06:14:33.000Z",
    "float": 3370395264.111782,
    "hash": 5859366,
    "int": 5859366,
    "join": "Parkway Street",
    "oneOf": "red",
    "oneOfWeighted": "blue",
    "paragraph": "Nesani ru rikìnu neko sayume ruyūko, mira nisemȏchi nirekowo chika ŝomu nuḟure kumemiro mutẹrami. Ramặ mehaṃe ra shiwaho m̃o fu ǩe, kamehe moteyuyu muṯsu heno yomoteru. Kỉ s̈ekahe shineku haǩe fuhashira nesa nanono tohatsu. Kȫmu kềnimaro ǩichiyo sű ya ku kato.",
    "sentence": "Neremufu raka fu ƫe niroẏu musehi suwoto yuṡhi.",
    "someOf": Array [
      "too",
      "think",
      "is",
    ],
    "times": Array [
      "Yuchi",
      "Niroroke",
      "Fuyayoha",
      "Narasa",
    ],
    "tuple": Array [
      "Parkway",
      "Street",
    ],
    "word": "Tsum̃i",
    "words": "To hite",
  },
  Object {
    "bool": true,
    "dateString": "2017-02-06T13:46:04.000Z",
    "float": 3370394115.2790723,
    "hash": 5859397,
    "int": 5859397,
    "join": "Parkway Road",
    "oneOf": "green",
    "oneOfWeighted": "green",
    "paragraph": "Kisḩina ꞩafu teǹoki fuchi mỡ kironukȃ, tořo toḫenuro yohehe muheteko mechiheho. Tomerỉho ḵehi koto mari ronuyoro ritachḯchi hehầ. Mumetoʈe newamihi mốsonuya rukichiyo ño mu kisokawõ. Narewaro raho fumoro so tasorona hahi yamene, he narona kimukoŵo kirȉse mimohiya. Tamehahi kokā̀motsu ḿu tasa sảno ƒurito soseyose, teto mesoshike wőchimoha sacḩike rikosu.",
    "sentence": "Rồ ro kaćhi hekokịhe rukurusu, yonokutsu su seyomi ṁo seḧa.",
    "someOf": Array [
      "i",
      "beautiful",
      "too",
      "256",
    ],
    "times": Array [
      "Muta",
      "Muɽu",
      "Hiku",
    ],
    "tuple": Array [
      "Parkway",
      "Road",
    ],
    "word": "Toriḥi",
    "words": "Hoťsuyuha mu nurohe",
  },
  Object {
    "bool": false,
    "dateString": "2008-09-09T20:17:35.000Z",
    "float": 3370397314.406751,
    "hash": 5859428,
    "int": 5859428,
    "join": "Cherry Road",
    "oneOf": "blue",
    "oneOfWeighted": "blue",
    "paragraph": "Nề ṇo wo soyử senewa. Ṣatanu yufu moriru su menenekǔ shi. Tarere wose chino nenike yake. Merite meyami rosamu hesahoshi keki.",
    "sentence": "Mệhami chiỹuhi wase wasako ᶄokuya.",
    "someOf": Array [
      "i",
      "is",
      "colors",
      "are",
      "beautiful",
    ],
    "times": Array [
      "Meyŭ",
      "Rişuto",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Miyomamu",
    "words": "Yuyutsu yu",
  },
  Object {
    "bool": true,
    "dateString": "1983-12-08T11:28:50.000Z",
    "float": 3370396421.377433,
    "hash": 5859203,
    "int": 5859203,
    "join": "Privet Street",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Woṁufu hichichi wo kurika kenḯyu sẳtsu m̃e, sehekoko mesaharī̀ se kinoko ri. Kuha kokam̃a yaroke ke tḙnaworu ho tenawa yuhehi, nṏ ᶄotsu kumo rayokoṟo hokuso ẃo. Rani te yomu ṙi ha shifufu te, romekano shireẇase yuno murehiha yo wachiso. Moke wanoso nana fü wṏ kinahahe rɨhoma nasetsu, hono he chichikori moŗitsu makoyuko tsuyo nesṓke funi. Yumawowȁ ṇa kashimutắ yuneḫe ro ko.",
    "sentence": "So shirehiṡo raso r̃o mʉrutesa miheko nurakǟta, kano hireseňi nesufuto koshime rotarare fuhesačhi śu ńukuhi.",
    "someOf": Array [
      "are",
      "you",
      "that",
      "think",
      "beautiful",
    ],
    "times": Array [
      "Yoruni",
      "Hatầse",
      "Yoki",
      "Sę̃ku",
      "Fufukiko",
    ],
    "tuple": Array [
      "Privet",
      "Street",
    ],
    "word": "Semotsume",
    "words": "Ṁa ha sufura",
  },
  Object {
    "bool": false,
    "dateString": "2014-07-11T19:00:21.000Z",
    "float": 3370399620.3419905,
    "hash": 5859234,
    "int": 5859234,
    "join": "Privet Road",
    "oneOf": "red",
    "oneOfWeighted": "red",
    "paragraph": "Sateharu muriȑese soseḿa wẚ horore nu ne totatsuhờ. Ṁufuniyu yarune ÿuya reyurese reȳaho chikoro nonunuhe sanuru, yų́ta ŝo ᶄu notsuṛifu hemiso rorikomu. Su nosoha ȟoku rawo kiku serunota. Tsura chitsu sukakuṝi tsu soyu, sa hateke fumuta ma yaro.",
    "sentence": "Chi wa ma yakiku nomaťe te yṓku.",
    "someOf": Array [
      "too",
      "are",
      "beautiful",
    ],
    "times": Array [
      "Rotase",
      "Kotsu",
      "Fuke",
      "Keram̃eso",
    ],
    "tuple": Array [
      "Privet",
      "Road",
    ],
    "word": "Rashi",
    "words": "Setakuta wằwayuso",
  },
  Object {
    "bool": true,
    "dateString": "2005-02-14T01:31:52.000Z",
    "float": 3370398471.135299,
    "hash": 5859265,
    "int": 5859265,
    "join": "Parkway Road",
    "oneOf": "green",
    "oneOfWeighted": "red",
    "paragraph": "Rḛ ta taya fuwoyoka yakimayo sunufuha rṷ ri, woserote yawo teyǡro taka hinasari chiṋo şhi sukanuȼhi. Ṁiyaru hê̌ nȇwo mokaruchi ƫe ki wo yofusa, kę́ susawanu ya hoķenitsu ruhirunu taçhitayo mⱥ rechi. Nohemite mi ruñisu shirawậma sawoše ro, tamo sằnoyare noñe yo ḩi. To yuhero hikiniyo suhekire saheyo rayonȗ nuke. Ketasashi ṙomine torosa muwawara mi, mane ką tama marokimi moworì su.",
    "sentence": "Hehi kǡ rakufuyu so makofự ri țenakosu ṣe, yumaku rṑhome ho mahi romushi kuhȍwoke meritsu kiňu.",
    "someOf": Array [
      "think",
      "beautiful",
      "colors",
      "that",
    ],
    "times": Array [
      "Niḩiya",
      "Shiwoyuya",
      "Yuhohḗto",
    ],
    "tuple": Array [
      "Parkway",
      "Road",
    ],
    "word": "Semito",
    "words": "Nayuho ċhi kako",
  },
  Object {
    "bool": false,
    "dateString": "1996-09-17T09:03:23.000Z",
    "float": 3370401670.1975164,
    "hash": 5859296,
    "int": 5859296,
    "join": "Privet Road",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Rukuku hi yộ hi so wowoẅaro, tệ nata kitsumuwo nukikuru kara mitsuhi ni. Hoyunoka waro momi yaworu seyonṹ hahǡtsu kakisu ri. Nare roteka shi mahanu woyậ musu moyahaṥe hotakŭ, mi ri mỗnahe yusumewa tsutanotsu nokenori. Tatŝusawa mukowowo yumumuha kurả ṥamimeto ⱦa hesanami, numika tsumohihi natorowo toṩu ra chifunu.",
    "sentence": "Seṛe me ḩa chiwaroku ḿifu.",
    "someOf": Array [
      "colors",
      "too",
      "beautiful",
      "think",
      "i",
    ],
    "times": Array [
      "Nehishitsu",
      "Nísana",
    ],
    "tuple": Array [
      "Privet",
      "Road",
    ],
    "word": "Kihemite",
    "words": "So kẫ",
  },
  Object {
    "bool": true,
    "dateString": "2019-12-13T00:11:26.000Z",
    "float": 3370383369.124164,
    "hash": 5859599,
    "int": 5859599,
    "join": "Cherry Street",
    "oneOf": "blue",
    "oneOfWeighted": "green",
    "paragraph": "Kewotachi mimomo raro ranishime raķu mẽmu, hinimu hirehowo wo̩kanu ka toraƫsumu chimotsu. Nu mufutafṻ hawasa mechirora muyuꞩa chiḿureku hầchiname. Yawa tofutoso mu sakahi nihḙtenu, ḧa keņo tenu nene nehổta tekimume ha. Raṁune reru satewayo tsumʉchino mu. Shỉ somộki nara nayu mehe mikeŧe miḫo tara.",
    "sentence": "Hiya rekukaku yawanaha nįso refūme, nanosaka teta ṩa kowaku shisekichi karesenu ni tạ.",
    "someOf": Array [
      "too",
      "is",
      "think",
      "it",
      "are",
    ],
    "times": Array [
      "Keteyá",
      "Mehe",
      "Roseko",
      "Nasafų́mu",
      "Yoyase",
    ],
    "tuple": Array [
      "Cherry",
      "Street",
    ],
    "word": "Torowofu",
    "words": "Tètone miri sakuru",
  },
  Object {
    "bool": false,
    "dateString": "2010-07-15T06:42:57.000Z",
    "float": 3370386568.2311926,
    "hash": 5859630,
    "int": 5859630,
    "join": "Parkway Street",
    "oneOf": "red",
    "oneOfWeighted": "green",
    "paragraph": "Ruruyuto tare tsumo mētemu meyaresṓ chika, sumumé̩ma nonuriku meniki kimitafu ru hasamo riŵakiro wo. Fṷhisumi ki tanamṑse keshisuko nurano ronǔ, hewokű chikẵso hayu rarǘno toṁoremu sehari sẽhiwate saso. Nusuki rutetesḁ re meḟunihe suḉhi. Mī̀suki tsumunuwa hor̃ukuke kato sḩi rekanȧko saḿiyo ḣetamomi.",
    "sentence": "Wǡ shi honi miwomoshi hana.",
    "someOf": Array [
      "beautiful",
      "256",
      "it",
    ],
    "times": Array [
      "Kumarḝmi",
      "Kushifu",
      "Yufűkare",
      "Reǹa",
    ],
    "tuple": Array [
      "Parkway",
      "Street",
    ],
    "word": "Mate",
    "words": "Tả memiku",
  },
  Object {
    "bool": false,
    "dateString": "1994-11-27T22:42:01.000Z",
    "float": 3370392096.759647,
    "hash": 5859334,
    "int": 5859334,
    "join": "Privet Street",
    "oneOf": "green",
    "oneOfWeighted": "red",
    "paragraph": "Hikura numumikē naya henu ƴo wa, meḣomi ka rȗ hiwo̩ kǐshi soni. Moyoheta hichikori kowakọ kiyo hihakaru kechi, kemoǩeko chiho mechimiwa tā̀yu neyậ yoru. Ró fȗ fusatsű neri fumu chiriri rề mohaḱeni, maso wỡ komiroke mể nuṥhirome wofusa. Wayuyu ņe ro nuwanito neshi, ŝe nowo na sa ṝawashiyu na.",
    "sentence": "Nu hiɽi chiṋatsuri ṣuriru honiḿiso.",
    "someOf": Array [
      "think",
      "too",
      "it",
      "that",
    ],
    "times": Array [
      "Ratoyuki",
      "Katệ",
      "Neri",
      "Kiki",
    ],
    "tuple": Array [
      "Privet",
      "Street",
    ],
    "word": "Yokerự",
    "words": "Ⱨinu sofusuru",
  },
  Object {
    "bool": true,
    "dateString": "1987-08-04T07:15:34.000Z",
    "float": 3370395361.3623056,
    "hash": 5859367,
    "int": 5859367,
    "join": "Cherry Street",
    "oneOf": "green",
    "oneOfWeighted": "blue",
    "paragraph": "Rukowo rakichi fu ṃo rom̃o sekomotsu ǩiyo, hofuțsusu ṃe fusoyumo wáseta nuhe nanoko kẹ. Rikaȑa hihî meŵa sehěkoka he, ma rukę̃ ɍo takuhehi tetetểyu yanihi mahaseto. Mḕ yochitsu riꞧunuki yaḿi sesu nayo. Saranira kunutsuhi ruyate ruyuma komanini se rutsu, nuho kimifu senỗ yominuku marutema hihi nuchiṣhihi ṟo. Ta chiwotḁ ḟuwara s̈e yǎte hemora me, yomayowò rayofuchi ya me mỉ suresane shiha fṻmo.",
    "sentence": "Hososa miru hehise nanetsǜ wo, rumuno no shi kűyanu ritasosa techinuwa.",
    "someOf": Array [
      "i",
      "think",
      "beautiful",
      "too",
    ],
    "times": Array [
      "Setŝu",
      "Rahihỡ",
      "Tsunoso",
      "Furiṁoho",
      "Heteka",
    ],
    "tuple": Array [
      "Cherry",
      "Street",
    ],
    "word": "C̈hikase",
    "words": "Sehosumu nisochi ru",
  },
  Object {
    "bool": false,
    "dateString": "2016-01-05T12:45:03.000Z",
    "float": 3370394146.153844,
    "hash": 5859396,
    "int": 5859396,
    "join": "Parkway Drive",
    "oneOf": "red",
    "oneOfWeighted": "blue",
    "paragraph": "Nerote kenehare rewokinu homuchiṃo mi reho. Tsuwahichi há şhihi kiwawa sere risetatsu sừkinohi. Fū tḙru wahe komi masașose henacḫifu. Ma tokanumo hi natsuhana kȋnoka hoḧa, katehe hise kứchiwo ỷu rẽ ṁekihe ḱisa.",
    "sentence": "Surärene kamaṁu rinuketsu ha konu tsuhiwachi.",
    "someOf": Array [
      "i",
      "256",
      "beautiful",
    ],
    "times": Array [
      "Toṣhi",
      "Tasachisả",
    ],
    "tuple": Array [
      "Parkway",
      "Drive",
    ],
    "word": "Homo",
    "words": "Yuranu soneta",
  },
  Object {
    "bool": true,
    "dateString": "2009-10-10T21:18:36.000Z",
    "float": 3370397411.2034492,
    "hash": 5859429,
    "int": 5859429,
    "join": "Parkway Street",
    "oneOf": "red",
    "oneOfWeighted": "blue",
    "paragraph": "Kè̩roniya ýa ḧe ho ᶄiru hoƙu. Taraḣiwa hi mesǚ kushi yunusana, nuko ra meni ṅu ŝehaya ne. To mechi yą̃ rofuchiri wonisese tomeyohe, sehoka nefủre noshishise yayutowa fuhahehi. Nato nukunu nakonatsu hi wanẻruso kuruhḛhe hæ, rimotena ṋorune mēwa mutaǩi moře. Yuyora toṙe kufų̃ maṃu wą́.",
    "sentence": "W̊omotsu kāmi sare ṃikawamo rochi totachi ⱨireyo, waniri nựtsu shisete chî ko teyo.",
    "someOf": Array [
      "i",
      "you",
      "that",
    ],
    "times": Array [
      "Kuwa",
      "Yawo",
      "Newaraya",
    ],
    "tuple": Array [
      "Parkway",
      "Street",
    ],
    "word": "Shim̃e",
    "words": "Sokū̃chi ma hesa",
  },
  Object {
    "bool": false,
    "dateString": "1982-11-07T10:27:49.000Z",
    "float": 3370396452.147253,
    "hash": 5859202,
    "int": 5859202,
    "join": "Parkway Street",
    "oneOf": "green",
    "oneOfWeighted": "red",
    "paragraph": "Womatsuso mishiraru hawariho sahomấ mokumu nȉ waroshichi rumahechi. Mu nĕho nosohe wokaheri mano ẉa keho yamiyoha, ku fukute maŵo hí rī nutoro ko. Warenena hⱥki tosefuno mira rohinų́ha kỏso. Shinirḝ tỗ merasầ wo tonima tonu wayonete mamoṃusa.",
    "sentence": "Nenuna kinaheta wayuroku ruhįni shihane hire sotoko.",
    "someOf": Array [
      "are",
      "that",
      "beautiful",
      "too",
    ],
    "times": Array [
      "Sȭma",
      "Nira",
      "Hari",
      "Ṫotochiha",
    ],
    "tuple": Array [
      "Parkway",
      "Street",
    ],
    "word": "Mḝmori",
    "words": "Shiteka wano",
  },
  Object {
    "bool": true,
    "dateString": "2015-08-12T20:01:22.000Z",
    "float": 3370399717.278102,
    "hash": 5859235,
    "int": 5859235,
    "join": "Privet Drive",
    "oneOf": "green",
    "oneOfWeighted": "red",
    "paragraph": "Suƙeya chike rusoshima rekusuċhi te. Ɽeho runųho mita ñe rota ⱪu ku. Shiḥo chirǫ shiyare rumemi wateko wahe koneku seẏawa. No ma yukõri ṱa wṍtomiro mikoya yuhi. Yuchiṇamo reho fuhiwa ho nokutoru wohoso.",
    "sentence": "Rene shimuteka nosonoto yo m̃onune maƫowayo morotowa safu, sonohe noworảka wasesose chim̃uwo tsu yonutsufu sushitaha.",
    "someOf": Array [
      "are",
      "that",
      "it",
      "i",
    ],
    "times": Array [
      "Tamuwasa",
      "Noruẅo",
      "Hasoma",
      "Suneme",
      "Mereyu",
    ],
    "tuple": Array [
      "Privet",
      "Drive",
    ],
    "word": "Kachihe",
    "words": "Rima sotomotsu ţeme",
  },
  Object {
    "bool": false,
    "dateString": "2004-01-13T00:30:51.000Z",
    "float": 3370398502.3840528,
    "hash": 5859264,
    "int": 5859264,
    "join": "Cherry Road",
    "oneOf": "red",
    "oneOfWeighted": "red",
    "paragraph": "Seshiko minotoma ȓe risaẖe ŧe, yosuki herḙ fuma yuhiniǩo he. Kuyukiki yasono șe ni ku ḳeshi susona yořihe. Ko woha sosử tsuni ra chi kẵki fu. Nehonesẖi nu wo yo ko chi mesȃha chihe.",
    "sentence": "Mema m̃okimi wafu koro musukậ sashiyu.",
    "someOf": Array [
      "beautiful",
      "is",
      "too",
    ],
    "times": Array [
      "Ninihehi",
      "Hese",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Mę́fu",
    "words": "Ku koyų́",
  },
  Object {
    "bool": true,
    "dateString": "1997-10-18T10:04:24.000Z",
    "float": 3370401767.316472,
    "hash": 5859297,
    "int": 5859297,
    "join": "Parkway Drive",
    "oneOf": "red",
    "oneOfWeighted": "blue",
    "paragraph": "Rư mu ẙo kayamocḫi rotohe rami. Hehakanu nutsusa hė̃musa chiyotama shirekane kuniwồto shitsu fusenito, sa chirina mȍra fuminổ hi rìha yū merero. Šune ꝁi nawamotsu yȗ kirachi tsuhaki. Nonenahi nayu tę́hikomi hahokane kikeḵi. Tė́ kớ se tomuta to na nirureku miwa.",
    "sentence": "Ḟure ho wanushine hitsuha roware, ka sonari remo roko kata rù kirimu.",
    "someOf": Array [
      "it",
      "256",
      "are",
    ],
    "times": Array [
      "Yuya",
      "Nomishi",
      "Kenumarò",
    ],
    "tuple": Array [
      "Parkway",
      "Drive",
    ],
    "word": "Techi",
    "words": "Yomuno su yanira",
  },
  Object {
    "bool": false,
    "dateString": "2018-11-11T23:10:25.000Z",
    "float": 3370383400.15343,
    "hash": 5859598,
    "int": 5859598,
    "join": "Parkway Drive",
    "oneOf": "green",
    "oneOfWeighted": "blue",
    "paragraph": "Kukumumo kuwas̈a saresuẙu rekakamu nisu. Rimumo teķu kesora kakifu hososo sunasowa ma, maka ta kirishi raha nuyoni kiriyufu kukuƫori ȟitaka. Moħe ɍesowate ḿeka hano toyā he, sosǡki monasuni numoke mesumaņi wasuso fu. Tohiho suwa ha kỉ nayohayŭ.",
    "sentence": "Numiyani yukishi kasohora ka kefu somuri ho.",
    "someOf": Array [
      "is",
      "that",
      "too",
      "colors",
    ],
    "times": Array [
      "Nushisaho",
      "Sesasechi",
      "Hetsuheyu",
      "Newa",
    ],
    "tuple": Array [
      "Parkway",
      "Drive",
    ],
    "word": "Horisu",
    "words": "Tềhasanu ṧema",
  },
  Object {
    "bool": true,
    "dateString": "2011-08-16T07:43:58.000Z",
    "float": 3370386665.334273,
    "hash": 5859631,
    "int": 5859631,
    "join": "Cherry Drive",
    "oneOf": "green",
    "oneOfWeighted": "blue",
    "paragraph": "Ya tosëwa muwani nehemasu kisuka. Nįfu ṯe raḿatsu suyổ ruta ɍuyowo ku. Mamawa tenatsuko ḳe netsǔmako rakeso fumo kitotashi tatsukoshi. Rimi roremi se tsu yowowaną̃ none ne. Yồroruta nẵ rorofute sataṃo rḕririta yoya ȑi.",
    "sentence": "Ḩa womawa muhaya suwarãto keha haki rosa, teno mi ro sase kochi.",
    "someOf": Array [
      "that",
      "colors",
      "256",
      "i",
    ],
    "times": Array [
      "Nusatenḯ",
      "Rafutṍ",
      "Rumura",
      "Somệ",
      "Mę̃no",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Nisatsu",
    "words": "Ka temireso mo",
  },
  Object {
    "bool": true,
    "dateString": "1989-06-22T17:36:56.000Z",
    "float": 3370392263.301539,
    "hash": 5859329,
    "int": 5859329,
    "join": "Parkway Drive",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Ṣo nemohona tsunashire muhë he kikỡ muwoṭsuho ho, rḙ tsuwoke sȭtsunuke hesaya sune nė̃. Resufuri ḿina nǐyu fusakṏ naharisa kera, mefuyoyu rachiku shiri wo nomo. Nito nukeri marọri sḩi ƙoreketo kaśoyoto, ka mḙrisatsu rare ku manaheno nokatsu hakahɵni. Ruruyu fusenato wȁkoke ŝe sɵ nirumu no. Womakuru yam̃u ḣe ńu muhimi, ĥi yuyo kukonekằ norakiho tokuta sorisetsu ḳe.",
    "sentence": "Wa mą̃ka seyote sẖishi woresomḕ ri funakato, ňu hamimầ so nû tsumaka ranateso̩.",
    "someOf": Array [
      "you",
      "it",
      "i",
      "beautiful",
      "are",
    ],
    "times": Array [
      "Rasuwome",
      "Kīka",
      "Hachini",
    ],
    "tuple": Array [
      "Parkway",
      "Drive",
    ],
    "word": "Suțenune",
    "words": "Kata tosảrare mamuharu",
  },
  Object {
    "bool": false,
    "dateString": "1980-01-25T00:08:27.000Z",
    "float": 3370395462.1595445,
    "hash": 5859360,
    "int": 5859360,
    "join": "Parkway Road",
    "oneOf": "red",
    "oneOfWeighted": "green",
    "paragraph": "Sḩiki hi fuso kiku se, no rawo he yomā̀ ʈetsu teseho heya. Momikōhi soteya yamuseme mo nuwa ƒu se. Toraha kimusero m̃atawa mukeŷu runiᶄame ꞧi kosotero. Sa nehe tefuchino teshîfutsu r̃akewo naninu, kite rumena ke kosane wayốwahi.",
    "sentence": "Nį̃wani tashimam̃i rono temễteni komowa kú wotashitsu nu.",
    "someOf": Array [
      "256",
      "that",
      "are",
    ],
    "times": Array [
      "Ṅihiko",
      "Fufuƙi",
    ],
    "tuple": Array [
      "Parkway",
      "Road",
    ],
    "word": "Nuko",
    "words": "Sekika komosomí",
  },
  Object {
    "bool": true,
    "dateString": "2015-12-04T11:44:02.000Z",
    "float": 3370394437.2638025,
    "hash": 5859395,
    "int": 5859395,
    "join": "Cherry Drive",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Taẁa homo te ḟu shi teshi sâ. Mutamochi seketą́ ri mikotemo ne, roṝishi no ŕarohano kuchishiṃi ŷa. Kiyuwa ḿame wakeyu kasem̃o hișomo, roroteno soso tsunuyuḿu tokiro sutaṅe ᶄa. Nonemi rả rase suchi rayume tsuraho. Ri royasase tsushini shishina chi tehḁhimi kanu rehimeni.",
    "sentence": "Menate ruronu muhe rerosa shī̀, wǟ yuke hirurefu sushȋsa ŝekuro sehochino.",
    "someOf": Array [
      "is",
      "think",
      "that",
      "256",
      "beautiful",
    ],
    "times": Array [
      "Sarahe",
      "Tsuwofufu",
      "Shiyu",
      "Nuhi",
      "Kumuyana",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Kesateki",
    "words": "Nutoyochi shĭ fukoyano",
  },
  Object {
    "bool": false,
    "dateString": "2006-07-07T18:15:33.000Z",
    "float": 3370397636.347197,
    "hash": 5859426,
    "int": 5859426,
    "join": "Cherry Road",
    "oneOf": "red",
    "oneOfWeighted": "red",
    "paragraph": "Hisȅre hoyàchi nowo na meshi yo na. Ta kamu tenimeme ṥe hȃkete kotero ẖoruyuyo. Kehę̃te moḟu neshi mayarü motɵro henusero ware machinosū́. Na sokể ẁo ha tokitsuyo sⱨi hokitẩ, sukuma kï rekaṁosu mê̄heyuro shiwó̩kako sⱨi kikɇnoto kȏchi.",
    "sentence": "Sewa ho kurochi nu mufune tsu tororɨya.",
    "someOf": Array [
      "colors",
      "i",
      "think",
    ],
    "times": Array [
      "Mafuroyo",
      "Hewawa",
      "Hichiwa",
      "Tohē",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Haru",
    "words": "Ḵaku rayuyo",
  },
  Object {
    "bool": true,
    "dateString": "1985-02-10T13:30:52.000Z",
    "float": 3370396355.145507,
    "hash": 5859205,
    "int": 5859205,
    "join": "Cherry Street",
    "oneOf": "green",
    "oneOfWeighted": "blue",
    "paragraph": "Kirehetsu fu tonaro tsuṩhi rohomima mishi wama remeketo. Rèchi chisoteke woteta hi ne yo to s̈aso, rehekine ko noǹo kikuta tsuha woki wowano komoru. Maki ḣo chi risaro sahậno. Me yonarimi chiyo keyake to setsuhiwo. Meno fushifu haŕaki řatenu rasehomu riyuyo nutonu.",
    "sentence": "Muruha nīhana rinu re chihò sa s̈usute, miḱerono yanosuyu ramo ĉhisoho kumuhoto shihikafu.",
    "someOf": Array [
      "that",
      "are",
      "it",
      "you",
    ],
    "times": Array [
      "Yakisu",
      "Sererunu",
      "Suřeni",
    ],
    "tuple": Array [
      "Cherry",
      "Street",
    ],
    "word": "Rumiri",
    "words": "Nesehesa nokaẖe kinaṅa",
  },
  Object {
    "bool": false,
    "dateString": "2016-09-13T21:02:23.000Z",
    "float": 3370399554.3260784,
    "hash": 5859236,
    "int": 5859236,
    "join": "Privet Drive",
    "oneOf": "blue",
    "oneOfWeighted": "blue",
    "paragraph": "Kikuhi m̃e hiyuworo somasu ma kero, kesekuyu satsűsu chi ṃayuna rata shina memuyo. Kihiki kuyurise tofuyori ro ŷayuyu ǹimo toku sŭ. Nuné ri mewoha tomume hé tote roǩahafu. Heyome serimo hosė́ hito nutototo.",
    "sentence": "Womeyune ẘo sanonema kayo sokê̌nu.",
    "someOf": Array [
      "i",
      "colors",
      "you",
      "are",
      "is",
    ],
    "times": Array [
      "Nikitesu",
      "Wộchi",
    ],
    "tuple": Array [
      "Privet",
      "Drive",
    ],
    "word": "Nomoriro",
    "words": "Kĩkiro sū̀",
  },
  Object {
    "bool": true,
    "dateString": "2011-08-20T07:37:58.000Z",
    "float": 3370398529.406939,
    "hash": 5859271,
    "int": 5859271,
    "join": "Cherry Drive",
    "oneOf": "green",
    "oneOfWeighted": "blue",
    "paragraph": "Hȍma ruhokoso se cḫi chiritena tanę naĥohe ro, ṧo samuko yumi resorora sǟ ṝaya romanimu misato. Hỉ tsute yomamo memonṓsu kako kộ hakoroka ki. Rocⱨito marų yoyosu reya kerusa. Heyo shihime ĉhineruna reʈsusore tsunata tato, muha sekenṍ na wasusena ne c̈himune chīki. Rimana ya neni re neniɽoni kotekutsu, chitệ hini tsusḛmuso wo moru futsuho.",
    "sentence": "Reḉhi mohechiyu meroshɨ kờki temakichi ta ṃa wo, shi mososhȉni ĉhiso memi sǿ risu.",
    "someOf": Array [
      "colors",
      "256",
      "think",
      "you",
    ],
    "times": Array [
      "Hẽtsuki",
      "Wawomė̃",
      "Mịnasa",
      "Rehesone",
      "Samu",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Hoꞩhinu",
    "words": "Rushitomi temesase ha",
  },
  Object {
    "bool": false,
    "dateString": "2002-03-23T14:09:29.000Z",
    "float": 3370401728.244299,
    "hash": 5859302,
    "int": 5859302,
    "join": "Cherry Drive",
    "oneOf": "blue",
    "oneOfWeighted": "red",
    "paragraph": "Nekuko so niriwo watsȗ nu munutoke meraṃa. Seya neheke hơ mewa sata ẗokomahe. Yuketero muťosure chi hiyoshįta yu cḧino tokǻwo ʈerani. Rerisa hinê̄ ẘa korereku yukiyuhí tore yuchikushi hemikoṉe.",
    "sentence": "Woⱨiyu yamu wahoyu rosa ṥaharahe raşo toratatsǘ.",
    "someOf": Array [
      "think",
      "is",
      "you",
      "too",
      "beautiful",
    ],
    "times": Array [
      "Remeto",
      "Nawa",
      "Wamuṃo",
      "Nanohi",
    ],
    "tuple": Array [
      "Cherry",
      "Drive",
    ],
    "word": "Hiyas̈uki",
    "words": "Soro hesesu",
  },
  Object {
    "bool": true,
    "dateString": "2013-06-06T18:05:20.000Z",
    "float": 3370383567.133981,
    "hash": 5859593,
    "int": 5859593,
    "join": "Cherry Road",
    "oneOf": "blue",
    "oneOfWeighted": "blue",
    "paragraph": "Nimikȋ ma në chi mokotsuro. Nihahenu nuyątoshi suḿeha ẁata mumĩniya miri fukẚnetsu yų, risa mimene nosehoshi sotetsumi he. Kuǩinasa rosakeni nesefuse rotsu ẘachiku kȃmashi. Ta kự r̃a hachitsuya țo kiyoka me mĭma, nỉru nachi yū́ ɏa hễ mowatsǜne. Kemu heħesomo tȅke muhi ruḧikoto kiminewa, ƫachi kisetoyā rȭseke kosare nokawo.",
    "sentence": "Nḯkowohe nami wo ra sumuhimi wamotashi fuƴaho ⱦeha, så waheka nosarȃya mu tayara kirenutsu.",
    "someOf": Array [
      "that",
      "are",
      "think",
      "i",
      "you",
    ],
    "times": Array [
      "Ṯatetono",
      "Yokasoka",
      "Ƒusuho",
    ],
    "tuple": Array [
      "Cherry",
      "Road",
    ],
    "word": "Shỉkasuki",
    "words": "Henoṥu sa to",
  },
  Object {
    "bool": false,
    "dateString": "2004-01-09T00:36:51.000Z",
    "float": 3370386766.428754,
    "hash": 5859624,
    "int": 5859624,
    "join": "Parkway Street",
    "oneOf": "red",
    "oneOfWeighted": "red",
    "paragraph": "Somachima nĕhehamo tahiyaka wariḿere tsusu hayakahe ná. Wanu sashirani rahama wachiruso ranato tafu kamo. Hamồ korowo ṙo chiteke tohem̃aro ȓechiwo mashimi ni. Rutäyume shiwomĩso wasenunu są̃ woṁoru rutote.",
    "sentence": "Mį kiyoçhime miheyuho cḥisahemi rumiyoke şa hi.",
    "someOf": Array [
      "256",
      "it",
      "i",
    ],
    "times": Array [
      "Hikiko",
      "Morishi",
    ],
    "tuple": Array [
      "Parkway",
      "Street",
    ],
    "word": "Haha",
    "words": "Na koŕususo",
  },
]
`
